account/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='user_profile'),
    path('password_reset/', UserPasswordResetView.as_view(),
         name='user_password_reset'),
    path('password_reset/done/', UserPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/complete/', UserPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('follow/<int:user_id>/',
         UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/',
         UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user', EditUserView.as_view(), name='edit_user'),
]

notes/urls.py
from django.urls import path
from .views import *

app_name = 'notes'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('note/<int:note_id>/<slug:note_slug>/',
         NoteDetailsView.as_view(), name='note_details'),
    path('note/delete/<int:note_id>/',
         NoteDeleteView.as_view(), name='note_delete'),
    path('note/update/<int:note_id>/',
         NoteUpdateView.as_view(), name='note_update'),
    path('note/create/', NoteCreateView.as_view(), name='note_create'),
    path('reply/<int:note_id>/<int:comment_id>/',
         NoteReplyView.as_view(), name='note_reply'),
    path('like/<int:note_id>/', NoteLikeView.as_view(), name='note_like'),
]

social_notebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls', namespace='notes')),
    path('account/', include('account.urls', namespace='account')),
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Note(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='notes')
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=60)
    body = models.TextField()
    is_public = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'slug'],
                name='unique_note_slug_per_user'
            )
        ]

    def __str__(self):
        return f'{self.slug} / {self.updated}'

    def get_absolute_url(self):
        return reverse("notes:note_details", args=(self.pk, self.slug))

    def likes_count(self):
        return self.note_like.count()


class Comment(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_comments')
    note = models.ForeignKey(
        Note, on_delete=models.CASCADE, related_name='note_comments')
    reply = models.ForeignKey(
        'self', on_delete=models.CASCADE, related_name='replies', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.body[:15]}'


class Like(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_like')
    note = models.ForeignKey(
        Note, on_delete=models.CASCADE, related_name='note_like')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'note'],
                name='unique_like_per_user_note'
            )
        ]

    def __str__(self):
        return f'{self.user.username} likes {self.note.title}'

notes/forms.py
from django import forms
from .models import Note, Comment


class NoteCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'body', 'is_public')


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'add comment for this note.'}),
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'reply to this comment'}),
        }


class NoteSearchForm(forms.Form):
    search = forms.CharField()

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Note, Comment, Like
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import NoteCreateUpdateForm, CommentCreateForm, CommentReplyForm, NoteSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
    form_class = NoteSearchForm

    def get(self, request):
        notes = Note.objects.all()
        if request.GET.get('search'):
            notes = notes.filter(body__contains=request.GET['search'])
        return render(request, 'home/index.html', {'notes': notes, 'form': self.form_class})


class NoteDetailsView(View):
    form_class = CommentCreateForm
    reply_form_class = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.note_instance = get_object_or_404(
            Note, pk=kwargs['note_id'], slug=kwargs['note_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = self.note_instance.note_comments.filter(is_reply=False)
        return render(request, 'home/note_details.html', {'note': self.note_instance, 'comments': comments, 'form': self.form_class(), 'reply_form': self.reply_form_class})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.note = self.note_instance
            new_comment.save()
            messages.success(
                request, 'Your comment submitted successfully.', 'success')
            return redirect('notes:note_details', self.note_instance.id, self.note_instance.slug)


class NoteDeleteView(LoginRequiredMixin, View):
    def get(self, request, note_id):
        note = get_object_or_404(Note, pk=note_id)
        if note.user.id == request.user.id:
            note.delete()
            messages.error(request, 'Note deleted.', 'success')
        else:
            messages.error(
                request, 'You are not the owner of this note.', 'danger')
        return redirect('notes:home')


class NoteUpdateView(LoginRequiredMixin, View):
    form_class = NoteCreateUpdateForm

    def setup(self, request, *args, **kwargs):
        self.note = get_object_or_404(Note, pk=kwargs['note_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        note = get_object_or_404(Note, pk=kwargs['note_id'])
        if not note.user.id == request.user.id:
            messages.error(
                request, 'You can just update your notes.', 'warning')
            return redirect('notes:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        note = self.note
        form = self.form_class(instance=note)
        return render(request, 'home/note_update.html', {'form': form, 'note': note})

    def post(self, request, *args, **kwargs):
        note = self.note
        form = self.form_class(request.POST, instance=note)
        if form.is_valid():
            tmp = form.save(commit=False)
            tmp.slug = slugify(form.cleaned_data['title'])
            tmp.save()
            messages.success(request, 'Note update successfully.', 'success')
            return redirect('notes:note_details', note.id, note.slug)


class NoteCreateView(LoginRequiredMixin, View):
    form_class = NoteCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, 'home/note_create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.slug = slugify(form.cleaned_data['title'])
            new_note.save()
            messages.success(request, 'Note created successfully', 'success')
            return redirect('notes:note_details', new_note.id, new_note.slug)


class NoteReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, note_id, comment_id):
        note = get_object_or_404(Note, id=note_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.note = note
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'reply added successfully.', 'success')
            return redirect('notes:note_details', note.id, note.slug)


class NoteLikeView(LoginRequiredMixin, View):
    def get(self, request, note_id):
        note = get_object_or_404(Note, id=note_id)
        likes = Like.objects.filter(note=note, user=request.user)
        if likes.exists():
            messages.error(
                request, 'You have already liked this note.', 'info')
        else:
            Like.objects.create(note=note, user=request.user)
            messages.success(request, 'You like this note!', 'success')
        return redirect('notes:note_details', note.id, note.slug)

notes/templates/home/index.html
{% extends "base.html" %}

{% block content %}
    <form action='' method='GET'>
        {{ form.as_p }}
        <input type='submit' value='Search'>
    </form><br>
    <h1>Last Notes</h1>
    <div class="card">
        {% for note in notes %}
            <div class="card-body">
                <a href={{ note.get_absolute_url }} class="card-title h4 link-offset-2 link-underline link-underline-opacity-0">{{ note.title }}</a>
                <p class="card-text">{{ note.body|truncatewords:5 }}</p>
            </div>
        {% endfor %}
    </div>
    
{% endblock content %}

notes/templates/home/note_create.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Create note'>
    </form>
{% endblock content %}

notes/templates/home/note_details.html
{% extends "base.html" %}

{% block content %}
    <div class="card text-center">
        <div class="card-header">
            By user: <a href={% url "account:user_profile" note.user.pk %}> {{ note.user.username }} </a>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ note.title }}</h5>
            <p class="card-text">{{ note.body }}</p>
        </div>
        {% if request.user.id == note.user.id %}
            <a href={% url "notes:note_delete" note.id %} class="btn btn-danger">Delete note</a>
            <br>
            <a href={% url "notes:note_update" note.id %} class="btn btn-info">Update note</a>
        {% endif %}
        <div class="card-footer text-body-secondary">
            Last update: {{ note.updated|date:"d-M-Y" }}
        </div>
        <a href={% url "notes:note_like" note.id %} class='btn btn-primary col-md-2'>Like {{ note.likes_count }}</a>
    </div>
    <hr>
    <p class="h3">Comments</p>
    {% for comment in comments %}
    <div class='card bg-dark text-white'>
        <div class='card-header'>
            <p class='h5'>{{ comment.user.username }} - {{ comment.created|timesince }} ago</p>
            <div class='card-body'>
                <p>
                    {{ comment.body }}
                </p>
                {% if request.user.is_authenticated %}

                    <form action={% url "notes:note_reply" note.id comment.id %} method='POST'>
                        {% csrf_token %}
                        {{ reply_form.as_p }}
                        <input type='submit' value='Send'>
                    </form>
                {% endif %}
                {% with replies=comment.replies.all %}
                {% for reply in replies %}
                    <p class='bg-primary p-3 m-3'>{{ reply.user.username }}
                        <br>
                        {{ reply.body }}
                    </p>
                    
                {% endfor %}
                {% endwith %}
            </div>
        </div>
    </div><br>
    {% empty %}
        <p class='h4'>Be the first comment for this note!</p>
    {% endfor %}

    <hr>
    {% if request.user.is_authenticated %}
        <p class='h5'>Add your comment here.</p>
        <form action="" method='POST' novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type='submit' value='Send'>
        </form>
    {% else %}
        <p class='alert alert-danger'>Login first and add comment for this note.</p>
    {% endif %}
{% endblock content %}

notes/templates/home/note_update.html
{% extends "base.html" %}

{% block content %}
    <h2>Update Note</h2>
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock content %}