account/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='user_profile'),
    path('password_reset/', UserPasswordResetView.as_view(),
         name='user_password_reset'),
    path('password_reset/done/', UserPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/complete/', UserPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('follow/<int:user_id>/',
         UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/',
         UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user', EditUserView.as_view(), name='edit_user'),
]

notes/urls.py
from django.urls import path
from .views import *

app_name = 'notes'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('note/<int:note_id>/<slug:note_slug>/',
         NoteDetailsView.as_view(), name='note_details'),
    path('note/delete/<int:note_id>/',
         NoteDeleteView.as_view(), name='note_delete'),
    path('note/update/<int:note_id>/',
         NoteUpdateView.as_view(), name='note_update'),
    path('note/create/', NoteCreateView.as_view(), name='note_create'),
    path('reply/<int:note_id>/<int:comment_id>/',
         NoteReplyView.as_view(), name='note_reply'),
    path('like/<int:note_id>/', NoteLikeView.as_view(), name='note_like'),
]

social_notebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls', namespace='notes')),
    path('account/', include('account.urls', namespace='account')),
]

templates/inc/message.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-success">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">Notebook</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href={% url "notes:home" %}>Home</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href={% url "account:user_profile" request.user.id %}>{{ request.user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href={% url "account:user_logout" %}>Logout</a>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link active text-white" aria-current="page" href={% url "account:user_register" %}>SignUp</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active text-white" aria-current="page" href={% url "account:user_login" %}>Login</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>